### ISSUE TITLE
'device' is not defined

### ISSUE THREAD

**Issue by xXchrizzoXx** [SiddhanthHegde/Custom-Neural-Style-Transfer#1]
Hey SiddhanthHegde,

if I try to run your code, I get this error:
`Traceback (most recent call last):
  File "train.py", line 45, in <module>
    content_image = load_image(r'content4.jpg')
  File "C:\Style Transfer Test\Custom-Neural-Style-Transfer-main\utils.py", line 15, in load_image
    return image.to(device)
NameError: name 'device' is not defined`

Can you help me with this?
I use Python 3.8 and the current version of the required dependancies (29.10.2020)

Kind Regards,
Chris

**Comment by SiddhanthHegde** [comment]
Hey Chris,

Thank you for raising this issue. This issue has now been resolved in #53126a1197ed212766ff20a2e91d17e029f5b301 commit.

Regards,
Sid

**Comment by xXchrizzoXx** [comment]
Hahahaha, this is what I just wanted to write:

"Hmm, it seams that I fixed it by adding `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` to utils.py .
Is this as intended, haha? :D"

**Comment by SiddhanthHegde** [comment]
> Hahahaha, this is what I just wanted to write:
> 
> "Hmm, it seams that I fixed it by adding `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` to utils.py .
> Is this as intended, haha? :D"

Well, it was. And you could have added this line and created a pull request. I would have merged your pull request xD.
If you still have unique ideas to add code to this repo and make it innovative go on. I would love to merge your request

**Comment by xXchrizzoXx** [comment]
> > Hahahaha, this is what I just wanted to write:
> > "Hmm, it seams that I fixed it by adding `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` to utils.py .
> > Is this as intended, haha? :D"
> 
> Well, it was. And you could have added this line and created a pull request. I would have merged your pull request xD.
> If you still have unique ideas to add code to this repo and make it innovative go on. I would love to merge your request

Alright, I actually made a few changes, I can share with you. But first I have to figure out, how to use the pull request function...

**Comment by NithinSGowda** [comment]
1) First click on fork button on the top right of your screen when you are in th repo page
2) Now you have a copy of this repo on your profile.
3) Now play with your edits on the code
4) Commit and push your changes to your forked repository
5) Then you get an option to create a pull request stating that your repo is n commits ahead of the original repo.
6) Create your pull request and add some comments on what you have modfifed.
7) The repo admin will then merge your request and you'll be noted as a contributor to this repo

**Comment by NithinSGowda** [comment]
> > > Hahahaha, this is what I just wanted to write:
> > > "Hmm, it seams that I fixed it by adding `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` to utils.py .
> > > Is this as intended, haha? :D"
> > 
> > 
> > Well, it was. And you could have added this line and created a pull request. I would have merged your pull request xD.
> > If you still have unique ideas to add code to this repo and make it innovative go on. I would love to merge your request
> 
> Alright, I actually made a few changes, I can share with you. But first I have to figure out, how to use the pull request function...

1. First click on fork button on the top right of your screen when you are in th repo page
2. Now you have a copy of this repo on your profile.
3. Now play with your edits on the code
4. Commit and push your changes to your forked repository
5. Then you get an option to create a pull request stating that your repo is n commits ahead of the original repo.
6. Create your pull request and add some comments on what you have modfifed.
7. The repo admin will then merge your request and you'll be noted as a contributor to this repo

**Comment by xXchrizzoXx** [comment]
> > > > Hahahaha, this is what I just wanted to write:
> > > > "Hmm, it seams that I fixed it by adding `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` to utils.py .
> > > > Is this as intended, haha? :D"
> > > 
> > > 
> > > Well, it was. And you could have added this line and created a pull request. I would have merged your pull request xD.
> > > If you still have unique ideas to add code to this repo and make it innovative go on. I would love to merge your request
> > 
> > 
> > Alright, I actually made a few changes, I can share with you. But first I have to figure out, how to use the pull request function...
> 
> 1. First click on fork button on the top right of your screen when you are in th repo page
> 2. Now you have a copy of this repo on your profile.
> 3. Now play with your edits on the code
> 4. Commit and push your changes to your forked repository
> 5. Then you get an option to create a pull request stating that your repo is n commits ahead of the original repo.
> 6. Create your pull request and add some comments on what you have modfifed.
> 7. The repo admin will then merge your request and you'll be noted as a contributor to this repo

Thank you NithinSGowda,

I think it worked :D
